# 聚合操作

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.86831786, 0.09903569, 0.09791885, 0.70998718, 0.73645186,
       0.80877589, 0.29250257, 0.67653421, 0.66298296, 0.71074155,
       0.83332945, 0.88814428, 0.27083535, 0.43231081, 0.93966687,
       0.29609865, 0.89155796, 0.04368554, 0.48780724, 0.81670129,
       0.37907806, 0.22897742, 0.33146844, 0.50086184, 0.30644651,
       0.68169742, 0.09505476, 0.1542184 , 0.63735681, 0.54617101,
       0.25892435, 0.12197688, 0.32017678, 0.9167283 , 0.61458744,
       0.35535329, 0.85901875, 0.97035462, 0.85142864, 0.92246595,
       0.99156345, 0.39557942, 0.7649149 , 0.94571683, 0.44260743,
       0.36212228, 0.23202953, 0.67181373, 0.3024392 , 0.62502674,
       0.98582062, 0.40967702, 0.15578312, 0.18270518, 0.51968297,
       0.96248615, 0.67677847, 0.81180575, 0.38812822, 0.00415713,
       0.15657381, 0.92456918, 0.55000449, 0.22101067, 0.05666295,
       0.57787631, 0.96383804, 0.7335729 , 0.17812321, 0.20349675,
       0.99192121, 0.840728  , 0.43196171, 0.11260656, 0.29320

In [3]:
sum(L)

50.57629988283484

In [4]:
np.sum(L)

50.576299882834874

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

154 ms ± 3.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
424 µs ± 17.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

2.934765140905071e-07

In [7]:
np.max(big_array)

0.9999987339157769

In [8]:
big_array.min()

2.934765140905071e-07

In [9]:
big_array.max()

0.9999987339157769

In [10]:
big_array.sum()

500173.75017721875

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.prod(X) # X中所有元素相乘

0

In [16]:
np.prod(X + 1)

20922789888000

In [17]:
np.mean(X)

7.5

In [18]:
np.median(X)

7.5

In [19]:
v = np.array([1, 1, 2, 2, 10])

In [20]:
np.mean(v)

3.2

In [21]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50) # 分位数

0.5007482217877701

In [23]:
np.median(big_array)

0.5007482217877701

In [24]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

2.934765140905071e-07
0.25023059711810497
0.5007482217877701
0.7500132551317839
0.9999987339157769


In [25]:
np.var(big_array) # 方差

0.08335370552099149

In [26]:
np.std(big_array) # 标准差

0.28871041810262316

In [27]:
X = np.random.normal(0, 1, size=1000000)

In [28]:
np.mean(X)

-0.000636087854624724

In [29]:
np.var(X)

0.9995519643651565

In [30]:
np.std(X)

0.9997759570849644

## 索引

In [31]:
np.min(X)

-4.593081363989293

In [32]:
np.argmin(X) # 返回最小值对应的索引值

884593

In [33]:
X[884593]

-4.593081363989293

In [34]:
np.argmax(X) # 返回最大值对应的索引值

490308

In [35]:
X[490308]

4.7547390404215735

In [36]:
np.max(X)

4.7547390404215735

## 排序和使用索引

In [37]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
np.random.shuffle(x)
x

array([13, 14,  0,  3,  9,  1,  4,  7, 10,  5,  2,  8,  6, 12, 11, 15])

In [39]:
np.sort(x) # 没有改变x的本身

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
x

array([13, 14,  0,  3,  9,  1,  4,  7, 10,  5,  2,  8,  6, 12, 11, 15])

In [42]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
X = np.random.randint(10, size=(4, 4))
X

array([[1, 4, 1, 5],
       [6, 1, 5, 3],
       [1, 4, 2, 8],
       [5, 1, 5, 0]])

In [44]:
np.sort(X)

array([[1, 1, 4, 5],
       [1, 3, 5, 6],
       [1, 2, 4, 8],
       [0, 1, 5, 5]])

In [45]:
np.sort(X, axis=1)

array([[1, 1, 4, 5],
       [1, 3, 5, 6],
       [1, 2, 4, 8],
       [0, 1, 5, 5]])

In [46]:
np.sort(X, axis=0)

array([[1, 1, 1, 0],
       [1, 1, 2, 3],
       [5, 4, 5, 5],
       [6, 4, 5, 8]])

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
X

array([[1, 4, 1, 5],
       [6, 1, 5, 3],
       [1, 4, 2, 8],
       [5, 1, 5, 0]])

In [49]:
np.random.shuffle(x)

In [50]:
x

array([ 6, 14,  5, 10,  4,  0,  8,  1,  2, 12, 11,  3,  7,  9, 13, 15])

In [51]:
np.argsort(x) # 返回在原来列表中值排序后的索引值

array([ 5,  7,  8, 11,  4,  2,  0, 12,  6, 13,  3, 10,  9, 14,  1, 15])

In [52]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  6, 14,  8, 12, 11, 10,  7,  9, 13, 15])

In [53]:
x

array([ 6, 14,  5, 10,  4,  0,  8,  1,  2, 12, 11,  3,  7,  9, 13, 15])

In [54]:
np.argpartition(x, 3)

array([ 7,  5,  8, 11,  4,  2,  0,  1,  6,  9, 10,  3, 12, 13, 14, 15])

In [55]:
X

array([[1, 4, 1, 5],
       [6, 1, 5, 3],
       [1, 4, 2, 8],
       [5, 1, 5, 0]])

In [57]:
np.argsort(X, axis=1)

array([[0, 2, 1, 3],
       [1, 3, 2, 0],
       [0, 2, 1, 3],
       [3, 1, 0, 2]])

In [58]:
np.argsort(X, axis=0)

array([[0, 1, 0, 3],
       [2, 3, 2, 1],
       [3, 0, 1, 0],
       [1, 2, 3, 2]])

In [59]:
np.argpartition(X, 2, axis=1)

array([[0, 2, 1, 3],
       [1, 3, 2, 0],
       [0, 2, 1, 3],
       [3, 1, 2, 0]])