# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X)) # 求给定一个数随机的排列，如给定100，则返回[0, 100)的随机数

In [8]:
shuffle_indexes

array([ 70, 114, 146,  22, 148, 101,  99, 111,  39, 133,   7,  63,  94,
        10, 125,  86,   5,  91,   6, 103,  93,  62, 129,  69,  33,  81,
        36,  20,  68, 134,  28, 130,   1,  58, 109,  15,  37,  96, 121,
        98,   4,  11,  97,  53, 122,  66,  60,  26, 138,  52,  19,  49,
        92, 110,  71,  78,  77,  34, 128,  44,  75, 119,  29,   0,  31,
        51, 142, 143,  59,  57, 127, 137,  88, 113,  95,  64, 149,  25,
       123,  90, 118,  56, 124,  87,   8,  61,  38, 135, 145,  24,  47,
       126,  40, 147,  79,  43,   9,  27,  85, 106,  54,  76, 100, 136,
       102,  55, 144, 141,  72, 105,   2,  35, 117,  73,  18,  89, 120,
       140, 116,  84,  48,  12, 107,  67, 132, 131,  80,  41,   3, 104,
        14, 139,  46,  74,  50,  83,  17, 115,  16,  45, 112,  32,  21,
        82,  30,  65, 108,  23,  13,  42])

In [9]:
test_ratio = 0.2

In [10]:
test_size = int(len(X) * test_ratio)

In [11]:
test_size

30

In [12]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [13]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [14]:
X_train.shape

(120, 4)

In [15]:
y_train.shape

(120,)

In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用我们的算法

In [17]:
# from playML.model_selection import train_test_split # 如果playML和本页面在同级目录可以直接这样导入

ModuleNotFoundError: No module named 'playML'

In [20]:
# 如果playML和本页面不在同级目录
# import sys
# sys.path.append(你要添加的路径)

# 或者
# sys.path.insert(0,你要添加的路径)
# 你可以print(sys.path)看下你要的路径添加进去了没有
import sys
sys.path.append("/Users/zhangxue/Documents/WorkSpace/PythonWorkSpace/Python3入门机器学习 经典算法与应用")
print(sys.path)

['/Users/zhangxue/Documents/WorkSpace/PythonWorkSpace/Python3入门机器学习 经典算法与应用/chapter04', '/Users/zhangxue/software/anaconda3/envs/python37/lib/python37.zip', '/Users/zhangxue/software/anaconda3/envs/python37/lib/python3.7', '/Users/zhangxue/software/anaconda3/envs/python37/lib/python3.7/lib-dynload', '', '/Users/zhangxue/software/anaconda3/envs/python37/lib/python3.7/site-packages', '/Users/zhangxue/software/anaconda3/envs/python37/lib/python3.7/site-packages/IPython/extensions', '/Users/zhangxue/.ipython', '/Users/zhangxue/Documents/WorkSpace/PythonWorkSpace/Python3入门机器学习 经典算法与应用/playML', '/Users/zhangxue/Documents/WorkSpace/PythonWorkSpace/Python3入门机器学习 经典算法与应用']


In [21]:
from playML.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [30]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [31]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [32]:
from playML.kNN import KNNClassifier

In [33]:
my_knn_clf = KNNClassifier(k=3)

In [34]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [35]:
y_predict = my_knn_clf.predict(X_test)

In [36]:
y_predict

array([2, 1, 0, 2, 1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 2, 0, 1,
       1, 2, 0, 1, 2, 2, 0, 1])

In [37]:
y_predict.shape

(30,)

In [38]:
y_predict == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [39]:
np.sum(y_predict == y_test)

30

In [40]:
np.sum(y_predict == y_test)/len(y_test)

1.0

## sklearn中的train_test_split

In [41]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [46]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [47]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
