# 精准度和召回率的平衡

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [6]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

/Users/zhangxue/software/anaconda3/envs/python37/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [7]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [8]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]])

In [9]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [10]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [11]:
log_reg.decision_function(X_test)[:10]

array([-21.410194  , -32.8936381 , -16.38814108, -79.80821714,
       -48.04872851, -24.19617843, -44.58192386, -24.27422947,
        -1.13753574, -18.99724408])

In [12]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
log_reg.predict_proba(X_test)[:10, 0]

array([1.        , 1.        , 0.99999992, 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.75722691, 0.99999999])

In [16]:
decision_scores = log_reg.decision_function(X_test)

In [17]:
np.min(decision_scores)

-85.69968682080051

In [18]:
np.max(decision_scores)

19.858547724195706

In [19]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [20]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]])

In [21]:
precision_score(y_test, y_predict_2)

0.96

In [22]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [23]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [24]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]])

In [25]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [26]:
recall_score(y_test, y_predict_3)

0.8888888888888888